### ISSUE TITLE
unable to test

### ISSUE THREAD

**Issue by parjanya** [Virtual-Insurance-Products/clim-web-demo#2]
I got curious about how would this work, and tried my best to run on my computer, without much luck. Finding the missing packages wasn’t specially hard; I might have missed something I did, but it was something like this:

- `git clone https://github.com/Virtual-Insurance-Products/Chapter31`
- `git clone https://github.com/gigamonkey/monkeylib-macro-utilities/`
- `git clone https://github.com/Virtual-Insurance-Products/web-utils`
- `git clone https://github.com/Virtual-Insurance-Products/vip-clim-core`
- `git clone https://github.com/gigamonkey/monkeylib-macro-utilities`
- `git clone https://github.com/Virtual-Insurance-Products/http-response`
- `git clone https://github.com/Virtual-Insurance-Products/session`
- `git clone https://github.com/gigamonkey/monkeylib-macro-utilities/`
- `git clone https://github.com/Virtual-Insurance-Products/simple-parser`
- `git clone https://github.com/Virtual-Insurance-Products/event-handlers`
- `git clone https://github.com/Virtual-Insurance-Products/web-transpiler`
- `git clone https://gitlab.common-lisp.net/frideau/fare-matcher.git`
- `git clone https://github.com/Virtual-Insurance-Products/web-monad`

> [package clim-internals]..........................
> ..................
> Read error between positions 6975 and 7154 in /home/edgard/quicklisp-ccl/local-projects/web-utils/functions.lisp.
> \> Error: Reader error: No external symbol named "PS1*" in package #<Package "PARENSCRIPT"> .

Here I edited the file to `::PS1*` instead of referring to an external symbol and it worked. Then:

> Read error between positions 32020 and 33914 in /home/edgard/quicklisp-ccl/local-projects/web-monad/web-monad.lisp.
> \> Error: There is no package named "JS" .

I guess this is from Franz’s `aserve`?

- `git clone https://github.com/Virtual-Insurance-Products/monads`
- `git clone https://github.com/franzinc/aserve`

> \> (ql:quickload :aserve)
> To load "aserve":
>  Load 1 ASDF system:
>    aserve
> ; Loading "aserve"
> [package net.html.generator]
> \> Error: There is no package named "EXCL"

Now I am stuck... I suspect that isn’t a free package?

Anyhow, a screenshot would be most welcome :). I’m building a dictionary interface (https://edgard.bikelis.com/dict/index.html) and this looks like it would be [very] handy. Besides, from the little I saw of the comments, this looks like a very intense project!

**Comment by vindarel** [comment]
> (ql:quickload :aserve)

FYI, I quickloaded the aserve that is in Quicklisp, without cloning it from Franz. I guess it's a portable library. I didn't get the `EXCL` error, but I couldn't finish the installation and test the demo either.

> screenshot

\+1 :)

**Comment by ppymdjr** [comment]
vindarel - what problem do you with the demo now? The aserve I'm using is the portable aserve, which is a fork of Franz's. The quicklisp one should do fine.

Is there another problem? You might need to use the gigamonkeys html package here in Chapter34, but I would think the monkey lib one *should* work.

**Comment by t1ch** [comment]
Hallo 

> vindarel - what problem do you with the demo now? The aserve I'm using is the portable aserve, which is a fork of Franz's. The quicklisp one should do fine.
> 
> Is there another problem? You might need to use the gigamonkeys html package here in Chapter34, but I would think the monkey lib one _should_ work.

I have tried to compile it and there are issues 
1) in some files there are references to a package called js this should be ps 
2) fare-matcher package is deprecated in favor of optima and one has to uncomment the definition of length=n-p in fare-utils as it is used in fare-matcher.
3) I am getting this stack-strace
There is no applicable method for the generic function:
  #<STANDARD-GENERIC-FUNCTION CLIM-INTERNALS::%ACCEPT #x3020027B30BF>
when called with arguments:
  (#<CLIM-INTERNALS::LIST-TYPE #x302003B7F01D>
   ((LIST CLIM-WEB-DEMO::TODO) :SEPARATOR-REGEX "^\\n") NIL
   #<CLIM-WEB-DEMO::ORG-VIEW #x302003B7F0DD> :ERROR-IF-NOT-EOF
   NIL :DEFAULT NIL)
   [Condition of type NO-APPLICABLE-METHOD-EXISTS]

Restarts:
 0: [CONTINUE] Try calling it again
 1: [LOAD-SOURCE] Load "home:quicklisp;local-projects;clim-web-demo;todo.lisp" instead of "/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl"
 2: [RECOMPILE] Compile "home:quicklisp;local-projects;clim-web-demo;todo.lisp" into "/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl" then load "/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl" again
 3: [RETRY-LOAD] Retry loading #P"/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl"
 4: [SKIP-LOAD] Skip loading #P"/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl"
 5: [LOAD-OTHER] Load other file instead of #P"/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl"
 --more--

Backtrace:
  0: (#<CCL::STANDARD-KERNEL-METHOD NO-APPLICABLE-METHOD (T)> #<STANDARD-GENERIC-FUNCTION CLIM-INTERNALS::%ACCEPT #x3020027B30BF> #<CLIM-INTERNALS::LIST-TYPE #x302003B7F01D> ((LIST CLIM-WEB-DEMO::TODO) ..)..
  1: (NIL #<Unknown Arguments>)
  2: (#<STANDARD-METHOD CLIM-INTERNALS:STREAM-ACCEPT (T T)> NIL ((LIST CLIM-WEB-DEMO::TODO) :SEPARATOR-REGEX "^\\n") :VIEW #<CLIM-WEB-DEMO::ORG-VIEW #x302003B7F0DD> :ERROR-IF-NOT-EOF NIL :DEFAULT NIL :DELI..
  3: (CCL::%%CHECK-KEYWORDS #(2 #(:DELIMITER-GESTURES :DEFAULT :ERROR-IF-NOT-EOF :VIEW) #<METHOD-FUNCTION CLIM-INTERNALS:STREAM-ACCEPT (T T)>) 17510271285961)
  4: (NIL #<Unknown Arguments>)
  5: (CLIM-INTERNALS:ACCEPT ((LIST CLIM-WEB-DEMO::TODO) :SEPARATOR-REGEX "^\\n") :STREAM NIL :DELIMITER-GESTURES :EOF :ALLOW-COMMAND-INVOCATION T :NAME NIL :VIEW #<CLIM-WEB-DEMO::ORG-VIEW #x302003B7F0DD> :..
  6: (#<Anonymous Function #x302003B7F45F>)
  7: (CCL::$FASL-LFUNCALL #<CCL::FASLSTATE #x7F6788138FBD>)
  8: (CCL::%FASLOAD "/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl" #(#<Compiled-function CCL::$FASL-NOOP (Non-Global)  #x30000012869F> ..
  9: (CCL::%LOAD #P"/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl" NIL NIL :ERROR :DEFAULT NIL)
 10: (LOAD #P"/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST :ERROR :EXTERNAL-FORMAT :DEFAULT..
 11: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<COMPILED-LEXICAL-CLOSURE (:INTERNAL UIOP/LISP-BUILD:LOAD*) #x302003B49C0F> ("Overwriting already existing readtable ~S." ..))
 12: (CCL::%%BEFORE-AND-AFTER-COMBINED-METHOD-DCODE ((NIL) #<STANDARD-METHOD ASDF/ACTION:PERFORM (ASDF/LISP-ACTION:LOAD-OP ASDF/LISP-ACTION:CL-SOURCE-FILE)> #<LOAD-OP> ..))
 13: (CCL::%CALL-NEXT-METHOD ((NIL) #<STANDARD-METHOD ASDF/ACTION:PERFORM (ASDF/LISP-ACTION:LOAD-OP ASDF/LISP-ACTION:CL-SOURCE-FILE)> #<LOAD-OP> #<CL-SOURCE-FILE "clim-web-demo" "todo">))
 14: ((:INTERNAL ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
 15: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<STANDARD-METHOD ASDF/ACTION:PERFORM :AROUND (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)> (#<STANDARD-METHOD ASDF/ACTION:PERFORM :BEFORE #>) ..)) 17510..
 16: (NIL #<Unknown Arguments>)
 17: (CCL::%CALL-NEXT-METHOD (NIL #<STANDARD-METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (T T)> . 17510271286214))
 18: (#<STANDARD-METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (ASDF/LISP-ACTION:LOAD-OP ASDF/LISP-ACTION:CL-SOURCE-FILE)> #<LOAD-OP> #<CL-SOURCE-FILE "clim-web-demo" "todo">)
 19: (CCL::%CALL-NEXT-METHOD (NIL #<STANDARD-METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (T T)> . 17510271286214))
 --more--

**Comment by ppymdjr** [comment]
OK - I've finally got the whole thing working with a *fresh* installation of quicklisp. I've updated the README file's quickstart section to describe the exact steps needed to test this. I've had to upload a few more libraries and I found a parenscript commit that this works with. Hopefully people should be able to try it now :)

**Comment by ppymdjr** [comment]
> Hallo
> 
> > vindarel - what problem do you with the demo now? The aserve I'm using is the portable aserve, which is a fork of Franz's. The quicklisp one should do fine.
> > Is there another problem? You might need to use the gigamonkeys html package here in Chapter34, but I would think the monkey lib one _should_ work.
> 
> I have tried to compile it and there are issues
> 
> 1. in some files there are references to a package called js this should be ps
> 2. fare-matcher package is deprecated in favor of optima and one has to uncomment the definition of length=n-p in fare-utils as it is used in fare-matcher.
> 3. I am getting this stack-strace
>    There is no applicable method for the generic function:
>    #<STANDARD-GENERIC-FUNCTION CLIM-INTERNALS::%ACCEPT #x3020027B30BF>
>    when called with arguments:
>    (#<CLIM-INTERNALS::LIST-TYPE #x302003B7F01D>
>    ((LIST CLIM-WEB-DEMO::TODO) :SEPARATOR-REGEX "^\n") NIL
>    #<CLIM-WEB-DEMO::ORG-VIEW #x302003B7F0DD> :ERROR-IF-NOT-EOF
>    NIL :DEFAULT NIL)
>    [Condition of type NO-APPLICABLE-METHOD-EXISTS]
> 
> Restarts:
> 0: [CONTINUE] Try calling it again
> 1: [LOAD-SOURCE] Load "home:quicklisp;local-projects;clim-web-demo;todo.lisp" instead of "/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl"
> 2: [RECOMPILE] Compile "home:quicklisp;local-projects;clim-web-demo;todo.lisp" into "/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl" then load "/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl" again
> 3: [RETRY-LOAD] Retry loading #P"/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl"
> 4: [SKIP-LOAD] Skip loading #P"/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl"
> 5: [LOAD-OTHER] Load other file instead of #P"/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl"
> --more--
> 
> Backtrace:
> 0: (#<CCL::STANDARD-KERNEL-METHOD NO-APPLICABLE-METHOD (T)> #<STANDARD-GENERIC-FUNCTION CLIM-INTERNALS::%ACCEPT #x3020027B30BF> #<CLIM-INTERNALS::LIST-TYPE #x302003B7F01D> ((LIST CLIM-WEB-DEMO::TODO) ..)..
> 1: (NIL #)
> 2: (#<STANDARD-METHOD CLIM-INTERNALS:STREAM-ACCEPT (T T)> NIL ((LIST CLIM-WEB-DEMO::TODO) :SEPARATOR-REGEX "^\n") :VIEW #<CLIM-WEB-DEMO::ORG-VIEW #x302003B7F0DD> :ERROR-IF-NOT-EOF NIL :DEFAULT NIL :DELI..
> 3: (CCL::%%CHECK-KEYWORDS #(2 #(:DELIMITER-GESTURES :DEFAULT :ERROR-IF-NOT-EOF :VIEW) #<METHOD-FUNCTION CLIM-INTERNALS:STREAM-ACCEPT (T T)>) 17510271285961)
> 4: (NIL #)
> 5: (CLIM-INTERNALS:ACCEPT ((LIST CLIM-WEB-DEMO::TODO) :SEPARATOR-REGEX "^\n") :STREAM NIL :DELIMITER-GESTURES :EOF :ALLOW-COMMAND-INVOCATION T :NAME NIL :VIEW #<CLIM-WEB-DEMO::ORG-VIEW #x302003B7F0DD> :..
> 6: (#<Anonymous Function #x302003B7F45F>)
> 7: (CCL::$FASL-LFUNCALL #<CCL::FASLSTATE #x7F6788138FBD>)
> 8: (CCL::%FASLOAD "/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl" #(#<Compiled-function CCL::$FASL-NOOP (Non-Global) #x30000012869F> ..
> 9: (CCL::%LOAD #P"/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl" NIL NIL :ERROR :DEFAULT NIL)
> 10: (LOAD #P"/home/user/.cache/common-lisp/ccl-1.12-f98-linux-x64/home/user/quicklisp/local-projects/clim-web-demo/todo.lx64fsl" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST :ERROR :EXTERNAL-FORMAT :DEFAULT..
> 11: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<COMPILED-LEXICAL-CLOSURE (:INTERNAL UIOP/LISP-BUILD:LOAD*) #x302003B49C0F> ("Overwriting already existing readtable ~S." ..))
> 12: (CCL::%%BEFORE-AND-AFTER-COMBINED-METHOD-DCODE ((NIL) #<STANDARD-METHOD ASDF/ACTION:PERFORM (ASDF/LISP-ACTION:LOAD-OP ASDF/LISP-ACTION:CL-SOURCE-FILE)> # ..))
> 13: (CCL::%CALL-NEXT-METHOD ((NIL) #<STANDARD-METHOD ASDF/ACTION:PERFORM (ASDF/LISP-ACTION:LOAD-OP ASDF/LISP-ACTION:CL-SOURCE-FILE)> # #<CL-SOURCE-FILE "clim-web-demo" "todo">))
> 14: ((:INTERNAL ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
> 15: (CCL::%%STANDARD-COMBINED-METHOD-DCODE (#<STANDARD-METHOD ASDF/ACTION:PERFORM :AROUND (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)> (#<STANDARD-METHOD ASDF/ACTION:PERFORM :BEFORE #>) ..)) 17510..
> 16: (NIL #)
> 17: (CCL::%CALL-NEXT-METHOD (NIL #<STANDARD-METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (T T)> . 17510271286214))
> 18: (#<STANDARD-METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (ASDF/LISP-ACTION:LOAD-OP ASDF/LISP-ACTION:CL-SOURCE-FILE)> # #<CL-SOURCE-FILE "clim-web-demo" "todo">)
> 19: (CCL::%CALL-NEXT-METHOD (NIL #<STANDARD-METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (T T)> . 17510271286214))
> --more--

The above was due to a silly reason - you have to be in the clim-web directory when starting things up because it tries to load todos.org. I've documented that in the README.org

**Comment by vindarel** [comment]
Thanks for these updates.

Suggestion: put all the git clones into a Makefile or a script?

I quickly tried again, I cloned the Chapters 08 and 31 but I don't have GIGAMONKEY.HTML:

```
Read error between positions 1713 and 2057 in /home/vince/quicklisp/local-projects/http-response/http-response-macros.lisp.
> Error: There is no package named "COM.GIGAMONKEYS.HTML" .
> While executing: CCL::%PARSE-TOKEN, in process listener(1)
```
but I might need to properly clone everything.

**Comment by ppymdjr** [comment]
> Thanks for these updates.
> 
> Suggestion: put all the git clones into a Makefile or a script?
> 
> I quickly tried again, I cloned the Chapters 08 and 31 but I don't have GIGAMONKEY.HTML:
> 
> ```
> Read error between positions 1713 and 2057 in /home/vince/quicklisp/local-projects/http-response/http-response-macros.lisp.
> > Error: There is no package named "COM.GIGAMONKEYS.HTML" .
> > While executing: CCL::%PARSE-TOKEN, in process listener(1)
> ```
> 
> but I might need to properly clone everything.

I tested it on a different account on my machine by running the commands listed in the readme, so it should work. Let me know if you still have problems with it. For testing I did dump those commands into a shell script, then I cleaned out all the quicklisp/local-projects and the build cache and ran the shell script. Eventually it all worked that way.
